# Generated by Django 6.0.6 on 2026-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importanomaly',
            name='suggested_action',
            field=models.TextField(blank=True, default=''),
        ),
    ]
