# Generated by Django 6.0.6 on 2026-06-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_group_admin_email_group_description_group_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_settlements', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
