# Generated by Django 6.0.6 on 2026-06-14 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_user_code_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='admin', max_length=50, null=True),
        ),
    ]
