# Generated by Django 6.0.6 on 2026-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_admin_email_group_description_group_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='net_balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
